# Active Profile (h2 or mysql)
spring.profiles.active=h2
spring.application.name=productivity

# Server configuration
server.port=8080

# Logging config
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
